### ISSUE TITLE
Clean up Types

### ISSUE THREAD

**Issue by leogdion** [brightdigit/IPSWDownloads#2]
Clean up and refactor the types generated from the openapi file. Here's an example:
https://github.com/brightdigit/IPSWDownloads/commit/38b1b8e7def8b3d19e565392a8b9dc6089b53a5c#diff-bba7105ce034b73ea2157376d310c97d92721a7a87dd55d1f0765a7ec4b959d5

Take a look at the documentation for the generator here:
https://swiftpackageindex.com/apple/swift-openapi-generator/1.1.0/documentation/swift-openapi-generator

There's a WWDC 2023 talk as well somewhere.

You can look at IPSW's docs there:
https://ipswdownloads.docs.apiary.io/#

**Comment by devahmedshendy** [comment]
I loved reading the api docs from IPSW's [API Blueprint](https://help.apiary.io/api_101/api_blueprint_tutorial/) here: 
https://ipswdownloads.docs.apiary.io/api-description-document

**Comment by leogdion** [comment]
My next WIP article on it is here:
https://gitlab.com/BrightDigit/Public/brightdigit.com/-/blob/content/openapi-generator/Content/tutorials/swift-openapi-generator.md
